#!/bin/bash

export TOP_GFM_DIR=`pwd`
export CVMH_SRC_DIR=$TOP_GFM_DIR/model/cvmh
export CVMH_INSTALL_DIR=$TOP_GFM_DIR/web/model/cvmh_target

cd $TOP_GFM_DIR/model
git clone https://github.com/SCECcode/cvmh.git -b forGFM cvmh 
cd cvmh
./configure --prefix=$CVMH_INSTALL_DIR
cd model
./make_data_files.py -d cvmh1511 -u mei

cd $CVMH_SRC_DIR
make
make install

cp $TOP_GFM_DIR/model/GFM/GFM_box_10x10x1km_forPhil.vo $CVMH_INSTALL_DIR/model
cp $TOP_GFM_DIR/model/GFM/GFM_box_10x10x1km_forPhil_regionID@@ $CVMH_INSTALL_DIR/model
cp $TOP_GFM_DIR/model/GFM/GFM_box_10x10x1km_forPhil_temp_median@@ $CVMH_INSTALL_DIR/model
 
