#!/bin/bash

source setup/setup_cvmh.sh

uid=`whoami`

rm -rf $TOP_GFM_DIR/model/cvmh
rm -rf $TOP_GFM_DIR/web/model/cvmh_target
mkdir -p $TOP_GFM_DIR/web/model/cvmh_target

cd $TOP_GFM_DIR/model
git clone https://github.com/SCECcode/cvmh.git -b forGFM cvmh 
cd cvmh
aclocal
automake --add-missing
autoconf
./configure --prefix=$CVMH_INSTALL_PATH
cd model
./make_data_files.py -d cvmh1511 -u $uid

cd $CVMH_SRC_PATH
make
make install

 
